### PR TITLE
Bump littlefs to 2.6.1

### PR DESCRIPTION
**Pull request by jmecom**
Updates littlefs to the latest release, which incurs a disk version update. Tested locally with `pytest test`.

### CODE REVIEW

**Comment by jrast** [comment]
Hey @jmecom! Thanks for the PR. Some questions regarding the disk version upgdate:
- Does the new version still support reading the old format
- Is a FS in the old version automatically migrated to the new version?

And a general question: Do you think that it's not required to still support the creation of old file system versions?

**Comment by jmecom** [comment]
Hi @jrast

The new version automatically migrates to the new version, thereby supporting old versions.

In my opinion, if a consumer of this library wants to use the old file system version, they can check out a previous commit. I think it would be best if this package tracks the latest littlefs.

**Comment by jrast** [comment]
You're right. I will merge this and create a new release (probably version 0.6.0). I will also add a note / table in the docs to get an overview of which python-littlefs version bundles which littlefs version.

**Comment by jmecom** [comment]
Thanks!

**Pull request merged**
