### PR TITLE
Support for LittleFS v2.8

### PR DESCRIPTION
**Pull request by BrianPugh**
This PR is in preparation for [littlefs release v2.8](https://github.com/littlefs-project/littlefs/pull/877).

Notable changes (for littlefs-python):

* Ability to autodetect filesystem `block_count` when `cfg.block_count` is set to 0.
* Integrated the new `lfs_fs_grow` command that grows a filesystem.

This branch **has not yet updated the littlefs submodule**. That will be done once v2.8 is released (and this PR will be converted from draft).

### CODE REVIEW

**Comment by BrianPugh** [comment]
littlefs v2.8.0 has been officially released.

**Comment by jrast** [comment]
Again a big thank you @BrianPugh !

**Comment by BrianPugh** [comment]
@jrast I was wondering if you could do a v0.8.0 release? This is the last major blocker for releasing my [gnwmanager](https://github.com/BrianPugh/gnwmanager) project on pypi.

**Comment by jrast** [comment]
Done!

**Pull request merged**
